version: '3.8'

services:
  postgres:
    container_name: postgres-twitter-db
    image: postgres:16.3-alpine3.20
    ports:
      - "5431:5432"
    volumes:
      - "postgres-data-twitter-db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-twitter-bot
    ports:
      - "6380:6379"
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter_bot-scheduler
    command: >
      bash -c "alembic upgrade head && celery -A scheduler worker --beat -E --loglevel=info --concurrency=1"
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
      - FETCH_API_BASE_URL=${FETCH_API_BASE_URL}
      - CALLER_INTERVAL_HOURS_GENERATE=${CALLER_INTERVAL_HOURS_GENERATE}
      - CALLER_INTERVAL_HOURS_POST=${CALLER_INTERVAL_HOURS_POST}
      - TRIGGER_IMMEDIATE=${TRIGGER_IMMEDIATE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    volumes:
      - ./logs:/logs

  scheduler-ui:
    image: mher/flower:latest
    container_name: scheduler-ui
    ports:
      - "5555:5555"
    command: ["celery", "flower", "--broker=${REDIS_URL}"]
    depends_on:
      - redis
      - scheduler
    restart: unless-stopped

volumes:
  postgres-data-twitter-db:
